<?php

return [
    '@CommercialInformation' => '@КоммерческаяИнформация',
    '@SchemeVersion' => '@ВерсияСхемы',
    '@CreatedDate' => '@ДатаФормирования',
    'classifier_id' => 'ИдКлассификатора',
    'classifier' => 'Классификатор',
    'image' => 'Картинка',
    'weight' => 'Вес',
    'sku' => 'Артикул',
    'width' => 'Ширина',
    'length' => 'Длина',
    'height' => 'Высота',
    'properties' => 'Свойства',
    'property' => 'Свойство',
    'property_value' => 'ЗначенияСвойств',
    'variant_values' => 'ВариантыЗначений',
    'xml_value' => 'Значение',
    'multi' => 'Множественное',
    'categories' => 'Группы',
    'category' => 'Группа',
    'catalog' => 'Каталог',
    'products' => 'Товары',
    'product' => 'Товар',
    'offersPackage' => 'ПакетПредложений',
    'offers' => 'Предложения',
    'offer' => 'Предложение',
    'prices' => 'Цены',
    'price' => 'Цена',
    'priceId' => 'ИдТипаЦены',
    'priceItem' => 'ЦенаЗаЕдиницу',
    'currency' => 'Валюта',
    'quantity' => 'Количество',

    'id' => 'Ид',
    'name' => 'Наименование',
    'description' => 'Описание',
];